import type { Asset } from "@/lib/models";

export function buildBook1Assets(): Asset[] {
  return [
    {
      id: "PC-0001",
      name: "AIM-A",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-64GB; SSD-1TB; HDD-/; Processor-I9-12th gen; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0002",
      name: "AIM-A",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-64GB; SSD-1TB; HDD-/; Processor-I9-12th gen; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0003",
      name: "AIM-A",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-64GB; SSD-1TB; HDD-/; Processor-I9-12th gen; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0004",
      name: "AIM-A",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-64GB; SSD-1TB; HDD-/; Processor-I9-12th gen; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0005",
      name: "AIM-A",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-64GB; SSD-1TB; HDD-/; Processor-I9-12th gen; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0006",
      name: "AIM-B",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-32GB; SSD-500GB; HDD-1TB; Processor- AMD RYZEN 5; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0007",
      name: "AIM-B",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-32GB; SSD-500GB; HDD-1TB; Processor- AMD RYZEN 5; GPU-8 GB RTX 3060 TI",
    },
    {
      id: "PC-0008",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C01",
    },
    {
      id: "PC-0009",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C14",
    },
    {
      id: "PC-0010",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C07",
    },
    {
      id: "PC-0011",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C19",
    },
    {
      id: "PC-0012",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C29",
    },
    {
      id: "PC-0013",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C13",
    },
    {
      id: "PC-0014",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C20",
    },
    {
      id: "PC-0015",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C04",
    },
    {
      id: "PC-0016",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C06",
    },
    {
      id: "PC-0017",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
      serial: "C15",
    },
    {
      id: "PC-0018",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0019",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0020",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0021",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0022",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0023",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0024",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0025",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0026",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0027",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0028",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0029",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0030",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0031",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0032",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0033",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0034",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0035",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0036",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0037",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0038",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0039",
      name: "AIM-C",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-1TB; HDD-/; Processor- AMD RYZEN 5; GPU-8 GB AMD RADION RX 6600",
    },
    {
      id: "PC-0040",
      name: "AIM-D",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-48GB; SSD-1TB; HDD-/; Processor-AMD RYZEN 7; GPU-8GB RADION RX 580 2048 SP",
    },
    {
      id: "PC-0041",
      name: "AIM-D",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-48GB; SSD-1TB; HDD-/; Processor-AMD RYZEN 7; GPU-8GB RADION RX 580 2048 SP",
    },
    {
      id: "PC-0042",
      name: "AIM-E",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-48GB; SSD-1TB; HDD-/; Processor-AMD RYZEN 7; GPU-4GB RTX 730",
    },
    {
      id: "PC-0043",
      name: "AIM-E",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-48GB; SSD-1TB; HDD-/; Processor-AMD RYZEN 7; GPU-4GB RTX 730",
    },
    {
      id: "PC-0044",
      name: "AIM-F",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-500GB; HDD-/; Processor- I5; GPU-4 GB RTX 730",
    },
    {
      id: "PC-0045",
      name: "AIM-F",
      category: "Desktop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-16GB; SSD-500GB; HDD-/; Processor- I5; GPU-4 GB RTX 730",
    },
    {
      id: "LAP-0001",
      name: "Laptop workstation",
      category: "Laptop",
      assignedTo: null,
      department: "IT",
      status: "Active",
      specifications: "Ram-32GB; SSD-1TB; HDD-/; Processor-I7 12th gen; GPU-8 GB RTX 3070 TI",
    },
    {
      id: "MON-0001",
      name: "Lenovo monitor",
      category: "Monitor",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "MON-0002",
      name: "ThinkCentre monitor",
      category: "Monitor",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "MON-0003",
      name: "AOC monitor",
      category: "Monitor",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "MON-0004",
      name: "Samsung monitor",
      category: "Monitor",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "ACC-0001",
      name: "Mouse",
      category: "Accessory",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "ACC-0002",
      name: "Keyboard",
      category: "Accessory",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
    {
      id: "ACC-0003",
      name: "Headset",
      category: "Accessory",
      assignedTo: null,
      department: "IT",
      status: "Active",
    },
  ];
}
