import type { Asset } from "@/lib/models";

/**
 * Sheet "PCs and Specifications" from Assets Data 2025.xlsx
 * Columns: S No → serial, Name → name, Desk → location,
 * Accessories + Softwares → specifications.
 * Regenerate: npm run import:assets-2025
 */
export function buildAssetsData2025(): Asset[] {
  return [
    {
      id: "PC-A01",
      name: "A01",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "1",
      location: "Desk-04",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-A02",
      name: "A02",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "2",
      location: "Desk-06",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-A03",
      name: "A03",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "3",
      location: "Desk-01",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-A04",
      name: "A04",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "4",
      location: "Desk-02",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-A05",
      name: "A05/ iso plugin",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "5",
      location: "Desk-08",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-B01",
      name: "B01",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "6",
      location: "Desk(S)-34",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-B02",
      name: "B02",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "7",
      location: "Desk-27",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C01",
      name: "C01",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "8",
      location: "Desk-05",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C02",
      name: "C02",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "9",
      location: "Desk-03",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C03",
      name: "C03",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "10",
      location: "Desk-16",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C04",
      name: "C04",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "11",
      location: "Desk-17",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C05",
      name: "C05",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "12",
      location: "Desk-18",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C06",
      name: "C06",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "13",
      location: "Desk-13",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C07",
      name: "C07",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "14",
      location: "Desk-14",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C08",
      name: "C08",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "15",
      location: "Desk-15",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C09",
      name: "C09",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "16",
      location: "Desk-10",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C10",
      name: "C10",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "17",
      location: "Desk-11",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C11",
      name: "C11",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "18",
      location: "Desk-12",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C12",
      name: "C12/ iso plugin",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "19",
      location: "Desk-09",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C13",
      name: "C13",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "20",
      location: "Desk-07",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C14",
      name: "C14",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "21",
      location: "Desk-21",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C15",
      name: "C15 /\u00a0 iso plugin",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "22",
      location: "Desk-20",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C16",
      name: "C16",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "23",
      location: "Desk-19",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C17",
      name: "C17/ iso plugin",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "24",
      location: "Desk-22",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C18",
      name: "C18",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "25",
      location: "Desk-23",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C19",
      name: "C19",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "26",
      location: "Desk-24",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C20",
      name: "C20",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "27",
      location: "Desk-28",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C21",
      name: "C21",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "28",
      location: "Desk-29",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C22",
      name: "C22",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "29",
      location: "Desk-26",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C23",
      name: "C23",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "30",
      location: "Desk-25",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C24",
      name: "C24",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "31",
      location: "Desk-00",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C25",
      name: "C25",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "32",
      location: "Desk(S)-35",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C26",
      name: "C26",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "33",
      location: "Desk-31",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C27",
      name: "C27",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "34",
      location: "Desk-30",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C28",
      name: "C28",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "35",
      location: "Desk(S)-32",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
    {
      id: "PC-C29",
      name: "C29",
      category: "Desktop",
      assignedTo: null,
      department: null,
      status: "Active",
      warrantyUntil: null,
      lastServiceAt: null,
      serial: "36",
      location: "Desk(S)-33",
      purchaseDate: null,
      specifications: "Accessories: Net Speed, Cables, Keyboard, Mouse; Softwares: Revit 2024 and plugins, Navis 2024 and plugins, CAD,Excel, PDF Editor,Teams",
    },
  ];
}
